### ISSUE TITLE
Minikeypad grid overlay

### ISSUE THREAD

**Issue by WouterJansen** [realitymod/PRGallery#3]
make grid overlay toggle between nothing, normal and one with minikeypads

**Comment by senshi-x** [comment]
There's two ways we can address this:
Make it toggle
Restrict it to zoom levels

My old viewer only showed it starting from a "middle" zoom level, as I felt it useless when zoomed far out.

We could also do both.

I have implemented this already,but am currently rewriting the Graticule class to reduce its unnecessary considerable performance footprint. PR will follow once done.

**Comment by UTurista** [comment]
Since the toggle mechanic/icon is already present, I'd say to use it instead of being level bounded.

My original idea was to make the keypad visible (regardless of zoom level) when the grid was visible and the mouse hovering the respective grid.
But I'm not really going to do that so any solution will be welcome.

**Comment by senshi-x** [comment]
Interesting idea with the one-grid only. But I think the overall keypads makes more sense. People use it to grab screenshots and for BP stuff in the PRT, and there keypads are a lifesaver.

Toggle as in triple toggle? Main grid -> Main+ Sub grid -> no grid?

**Comment by UTurista** [comment]
> People use it to grab screenshots and for BP stuff in the PRT, and there keypads are a lifesaver.

I guess...

> Toggle as in triple toggle? Main grid -> Main+ Sub grid -> no grid?

Yap
